# Generated by Django 3.2.4 on 2021-06-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Код товара')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('url', models.URLField(max_length=100, unique=True, verbose_name='Ссылка')),
                ('img', models.URLField(max_length=150, verbose_name='Картинка')),
                ('age', models.CharField(max_length=20, verbose_name='Возраст')),
                ('gender', models.CharField(max_length=20, verbose_name='Пол')),
                ('year', models.IntegerField(blank=True, verbose_name='Год')),
                ('use', models.CharField(max_length=20, verbose_name='Использование')),
                ('pronation', models.CharField(max_length=30, verbose_name='Пронация')),
                ('article', models.CharField(max_length=30, verbose_name='Артикул')),
                ('season', models.CharField(max_length=30, verbose_name='Сезон')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='***')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Кроссовки',
                'db_table': 'products',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Стоимость')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Обновлено')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Популярность')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.products', verbose_name='Код товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Цены',
                'db_table': 'prices',
                'ordering': ['-rating', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InstockNagornaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='размер')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Обновлено')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Популярность')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.products', verbose_name='Код товара')),
            ],
            options={
                'db_table': 'instock_nagornaya',
            },
        ),
    ]
