# Generated by Django 3.2.4 on 2021-06-25 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instocknagornaya',
            options={'ordering': ['-rating', '-timestamp'], 'verbose_name': 'Остаток', 'verbose_name_plural': 'Наличие'},
        ),
        migrations.AddField(
            model_name='products',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Обновлено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
